### ISSUE TITLE
Permission HIGH_SAMPLING_RATE_SENSORS required when targeting Android 12

### ISSUE THREAD

**Issue by alejandrorosas** [square/seismic#24]
On android 12 a new permission has been added when the sampling rate is set to 0 microseconds. Would be possible to have this value configurable? Are we able to detect the shake gesture with a sampling rate lower than 200 Hz?

The issue that I'm getting right now when initializing the `ShakeDetector` is this one:

```
java.lang.SecurityException: To use the sampling rate of 0 microseconds, app needs to declare the normal permission HIGH_SAMPLING_RATE_SENSORS.
        at android.hardware.SystemSensorManager$BaseEventQueue.enableSensor(SystemSensorManager.java:790)
        at android.hardware.SystemSensorManager$BaseEventQueue.addSensor(SystemSensorManager.java:710)
        at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:209)
        at android.hardware.SensorManager.registerListener(SensorManager.java:823)
        at android.hardware.SensorManager.registerListener(SensorManager.java:730)
        at com.squareup.seismic.ShakeDetector.start(ShakeDetector.java:66)
        ...
``

**Comment by toharifqi** [comment]
Make sure to update the library to 1.0.3 to be able to use sensor delay parameter.

**Comment by marctatham** [comment]
I wonder if SensorManager.SENSOR_DELAY_GAME make a more sensible default for the lib to be using 

(though admittedly i'm assuming the majority of usecases are using this for some small things in the app, shake to show dialog or similar)
